###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
      #run: docker build ./c# -t aimvector/csharp:1.0.0
     
    - name: Build and push docker docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
       image: thiexco/custom-images/aimvector/csharp:1.0.0
       registry: docker.io
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
    
    

